### model
# model_name_or_path: /home/user/if/wang/models/saves/qwen3-4b/pre-training-rm-unified-feedback-600k
model_name_or_path: /home/user/if/wang/models/saves/qwen3-14b/pre-training-rm-unified-feedback-600k/checkpoint-4000

trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: skywork_ft_rm

template: qwen3
cutoff_len: 2048
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

enable_thinking: false

### output
output_dir: /home/user/if/wang/models/saves/qwen3-14b/sft-rm-skywork-v0.2
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

# save_steps: 500

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

## GRAM
gram_loss: true
gram_candidate_labels:
 - "A"
 - "B"
gram_label_smoothing: 0.1